name: Upload Latest Artifacts to Release

on:
  release:
    types: 
      - released

jobs:
  package:
    name: Release New Six Patches Of Pain
    runs-on: ubuntu-latest
    steps:
      - name: 'Get version'
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | cut -d 'v' -f 2)" >> $GITHUB_ENV
      - name: Download latest artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
      - name: Organize release files"
        run: |
          find ./ -mindepth 2 -type f -exec mv -t ./ -i '{}' +
          find . -type d -empty -delete
          mv "linux.zip" "Six-Patches-Of-Pain-${{ env.VERSION }}-Linux.zip"
          mv "macOS.zip" "Six-Patches-Of-Pain-${{ env.VERSION }}-Mac.zip"
          mv "windows.zip" "Six-Patches-Of-Pain-${{ env.VERSION }}-Windows.zip"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

